apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "purestorage.name" . }}-provisioner-rights
  labels:
    app: {{ template "purestorage.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.clusterrolebinding.roleref.name }}
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }} 
