apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "purestorage.name" . }}-provisioner-config
  namespace: {{ .Release.Namespace }} 
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  pure.json: |
    {
        "FlashArrays": [
            {
                "MgmtEndPoint": "10.231.128.12",
                "APIToken": "c626aec6-18b0-a8c9-1afa-3499093574bb"
            }
        ]
    }
