apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "purestorage.name" . }}-flex
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: {{ template "purestorage.name" . }}-flex
      labels:
        app: {{ template "purestorage.name" . }}-flex
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      containers:
      - name: {{ template "purestorage.name" . }}-flex
        image: "{{.Values.image.name}}:{{.Values.image.tag}}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        securityContext:
          privileged: true
        command:
          - "/pure-flex-daemon"
          - "--kubeletBaseDir=/kubelet-plugins"
          - "--debug"
          - "--daemon"
          - "install"
        volumeMounts:
        - name: config
          mountPath: /etc/pure
        - name: kubelet-plugins
          mountPath: /kubelet-plugins
        env:
        - name: PURE_DISCOVERY_CONF
          value: /etc/pure/pure.json
      volumes:
      - name: kubelet-plugins
        hostPath:
          path: /usr/libexec/kubernetes/kubelet-plugins
      - name: config
        configMap:
          name: {{ template "purestorage.name" . }}-provisioner-config
      tolerations:
{{ toYaml .Values.daemonset.tolerations | indent 8 }}
