apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "purestorage.name" . }}-provisioner
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "purestorage.name" . }}-provisioner
    spec:
      containers:
        - name: {{ template "purestorage.name" . }}-provisioner
          image: "{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          command:
            - /k8s-provisioner
            - '-logtostderr=false'
            - '-stderrthreshold=2'
          volumeMounts:
          - name: config
            mountPath: /etc/pure
          env:
          - name: PURE_DISCOVERY_CONF
            value: /etc/pure/pure.json
          - name: PURE_K8S_NAMESPACE
            value: k8s
      volumes:
        - name: config
          configMap:
            name: {{ template "purestorage.name" . }}-provisioner-config
