kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "purestorage.name" . }}
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: {{ template "purestorage.name" . }}-provisioner
parameters:
    backend: block
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "purestorage.name" . }}-file
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: {{ template "purestorage.name" . }}-provisioner
parameters:
    backend: file
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ template "purestorage.name" . }}-block
  labels:
    kubernetes.io/cluster-service: "true"
provisioner: {{ template "purestorage.name" . }}-provisioner
parameters:
    backend: block
